services:
  perses:
    image: persesdev/perses
    container_name: perses
    command: "--config=/etc/perses/config/config.yaml"
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./perses/config.yaml:/etc/perses/config/config.yaml
      - ./perses/project.yaml:/etc/perses/resources/project/project.yaml
      - ./built:/etc/perses/resources/dashboard
      