name: Dashboard-as-Code workflow

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:
jobs:
  dac:
    uses: perses/cli-actions/.github/workflows/dac.yaml@v0.1.0
    with:
      url: https://demo.perses.dev
      directory: ./dashboards
      server-validation: true
      cli_version: v0.51.0-beta.0
    secrets:
      username: ${{ secrets.DAC_USR }}
      password: ${{ secrets.DAC_PSW }}